//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string country { get; set; }
        public string age { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string job { get; set; }
        public string language { get; set; }
        public string talent { get; set; }
        public string facebook { get; set; }
        public string insta { get; set; }
        public string email { get; set; }
        public string youtube { get; set; }
        public string b_y { get; set; }
        public string b_m { get; set; }
        public string b_d { get; set; }
        public string height { get; set; }
        public string hope { get; set; }
        public System.DateTime rdate { get; set; }
        public Nullable<int> category { get; set; }
    }
}
