//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardFile
    {
        public int BF_idx { get; set; }
        public int BF_BD_idx { get; set; }
        public string BF_name { get; set; }
        public System.DateTime BF_wdate { get; set; }
        public int BF_useable { get; set; }
        public int BD_BM_idx { get; set; }
        public string BF_type { get; set; }
        public string department_id { get; set; }
        public string main_img { get; set; }
        public string machine_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public string user_id { get; set; }
        public string file_title { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual BoardMenu BoardMenu { get; set; }
        public virtual project_main project_main { get; set; }
        public virtual user user { get; set; }
    }
}
