//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Board()
        {
            this.BoardComment = new HashSet<BoardComment>();
            this.BoardFile = new HashSet<BoardFile>();
        }
    
        public int BD_idx { get; set; }
        public int BD_BM_idx { get; set; }
        public string BD_title { get; set; }
        public string BD_content { get; set; }
        public string BD_writer { get; set; }
        public string BD_password { get; set; }
        public int BD_hit { get; set; }
        public System.DateTime BD_wdate { get; set; }
        public Nullable<System.DateTime> BD_edate { get; set; }
        public Nullable<System.DateTime> BD_ddate { get; set; }
        public int BD_useable { get; set; }
        public string machine_id { get; set; }
        public Nullable<int> project_id { get; set; }
    
        public virtual BoardMenu BoardMenu { get; set; }
        public virtual project_main project_main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardComment> BoardComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardFile> BoardFile { get; set; }
    }
}
