//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_memo
    {
        public int idx { get; set; }
        public string company_id { get; set; }
        public string department_id { get; set; }
        public string user_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string gubun_type { get; set; }
        public System.DateTime write_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> work_date { get; set; }
        public int project_idx { get; set; }
        public string use_yn { get; set; }
        public string file_sn { get; set; }
    
        public virtual user user { get; set; }
        public virtual project_main project_main { get; set; }
    }
}
