//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMenus
    {
        public int idx { get; set; }
        public string company_id { get; set; }
        public string step_name { get; set; }
        public string step_url1 { get; set; }
        public string step_url2 { get; set; }
        public string step_auth { get; set; }
        public Nullable<System.DateTime> step_writedate { get; set; }
        public string step_index { get; set; }
        public string step_icon { get; set; }
        public int step_dept { get; set; }
        public int step_orderby { get; set; }
        public Nullable<bool> isused { get; set; }
    }
}
