//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Company_name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Inquiry { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> write_date { get; set; }
        public int gubun_code { get; set; }
    
        public virtual code_1 code_1 { get; set; }
    }
}
