//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_list
    {
        public int idx { get; set; }
        public Nullable<int> file_menu_id { get; set; }
        public string file_idx { get; set; }
        public string file_name { get; set; }
        public string file_pre_name { get; set; }
        public int file_size { get; set; }
        public int hit { get; set; }
        public string file_type { get; set; }
        public System.DateTime write_date { get; set; }
    
        public virtual file_menu file_menu { get; set; }
    }
}
