//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_ask
    {
        public int idx { get; set; }
        public string nationality { get; set; }
        public string city { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public string group_code { get; set; }
        public int room_count { get; set; }
        public int grade { get; set; }
        public string one_price { get; set; }
        public string user_name { get; set; }
        public string hp { get; set; }
        public string user_id { get; set; }
        public string email { get; set; }
        public string memo { get; set; }
        public System.DateTime write_date { get; set; }
        public string state { get; set; }
    }
}
