//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_e : DbContext
    {
        public db_e()
            : base("name=db_e")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bbs_comment> bbs_comment { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<BoardComment> BoardComment { get; set; }
        public virtual DbSet<BoardFile> BoardFile { get; set; }
        public virtual DbSet<BoardMenu> BoardMenu { get; set; }
        public virtual DbSet<cal_memo> cal_memo { get; set; }
        public virtual DbSet<CategoryMenus> CategoryMenus { get; set; }
        public virtual DbSet<code_auth> code_auth { get; set; }
        public virtual DbSet<code_index> code_index { get; set; }
        public virtual DbSet<code_main> code_main { get; set; }
        public virtual DbSet<code_nationality> code_nationality { get; set; }
        public virtual DbSet<code_project_state> code_project_state { get; set; }
        public virtual DbSet<code_time> code_time { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<file_list> file_list { get; set; }
        public virtual DbSet<file_menu> file_menu { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<hotel_ask> hotel_ask { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<machine> machine { get; set; }
        public virtual DbSet<my_work> my_work { get; set; }
        public virtual DbSet<New_work> New_work { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<project_act> project_act { get; set; }
        public virtual DbSet<project_dir> project_dir { get; set; }
        public virtual DbSet<project_main> project_main { get; set; }
        public virtual DbSet<project_main_back> project_main_back { get; set; }
        public virtual DbSet<QA> QA { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<work_list> work_list { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<v_mywork_project> v_mywork_project { get; set; }
        public virtual DbSet<v_new_work> v_new_work { get; set; }
    
        public virtual ObjectResult<j_mywork_project_Result> j_mywork_project(string user_id, string start_day, string end_day)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var start_dayParameter = start_day != null ?
                new ObjectParameter("start_day", start_day) :
                new ObjectParameter("start_day", typeof(string));
    
            var end_dayParameter = end_day != null ?
                new ObjectParameter("end_day", end_day) :
                new ObjectParameter("end_day", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<j_mywork_project_Result>("j_mywork_project", user_idParameter, start_dayParameter, end_dayParameter);
        }
    
        public virtual ObjectResult<mywork_report_Result> mywork_report(string user_id, string start_day, string end_day)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var start_dayParameter = start_day != null ?
                new ObjectParameter("start_day", start_day) :
                new ObjectParameter("start_day", typeof(string));
    
            var end_dayParameter = end_day != null ?
                new ObjectParameter("end_day", end_day) :
                new ObjectParameter("end_day", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mywork_report_Result>("mywork_report", user_idParameter, start_dayParameter, end_dayParameter);
        }
    
        public virtual ObjectResult<mywork_report_project_Result> mywork_report_project(string user_id, string start_day, string end_day, Nullable<int> project_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var start_dayParameter = start_day != null ?
                new ObjectParameter("start_day", start_day) :
                new ObjectParameter("start_day", typeof(string));
    
            var end_dayParameter = end_day != null ?
                new ObjectParameter("end_day", end_day) :
                new ObjectParameter("end_day", typeof(string));
    
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mywork_report_project_Result>("mywork_report_project", user_idParameter, start_dayParameter, end_dayParameter, project_idParameter);
        }
    }
}
