//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupertalentE : DbContext
    {
        public SupertalentE()
            : base("name=SupertalentE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Application_Ko> Application_Ko { get; set; }
        public virtual DbSet<code_1> code_1 { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Get_Course_Content> Get_Course_Content { get; set; }
        public virtual DbSet<Md_Image> Md_Image { get; set; }
        public virtual DbSet<Model_Data> Model_Data { get; set; }
        public virtual DbSet<Pay> Pay { get; set; }
        public virtual DbSet<TG_Image> TG_Image { get; set; }
        public virtual DbSet<Travel_Goods> Travel_Goods { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
    }
}
