//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model_Data()
        {
            this.Md_Image = new HashSet<Md_Image>();
        }
    
        public int id { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> M_season { get; set; }
        public string M_name { get; set; }
        public string M_country_img { get; set; }
        public string M_country { get; set; }
        public string M_city { get; set; }
        public string M_language { get; set; }
        public string M_content { get; set; }
        public string M_born { get; set; }
        public string M_age { get; set; }
        public string M_height { get; set; }
        public string MainImgPath { get; set; }
        public string M_insta { get; set; }
        public string M_facebook { get; set; }
        public string M_youtube { get; set; }
        public Nullable<System.DateTime> Rdate { get; set; }
        public string M_residence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Md_Image> Md_Image { get; set; }
    }
}
