//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int id { get; set; }
        public Nullable<int> merchant_uid { get; set; }
        public Nullable<int> imp_uid { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> TG_id { get; set; }
        public string TG_name { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public string Buyer_account { get; set; }
        public string Buyer_bank { get; set; }
        public string Buyer_name { get; set; }
        public string Buyer_email { get; set; }
        public string Buyer_phone { get; set; }
        public string Pay_method { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Cart_date { get; set; }
        public Nullable<System.DateTime> Pay_date { get; set; }
        public Nullable<System.DateTime> Cancel_date { get; set; }
    
        public virtual Travel_Goods Travel_Goods { get; set; }
    }
}
