//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travel_Goods()
        {
            this.Courses = new HashSet<Courses>();
            this.Pay = new HashSet<Pay>();
            this.TG_Image = new HashSet<TG_Image>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Category { get; set; }
        public string Course { get; set; }
        public string Meeting_place { get; set; }
        public string Benefits { get; set; }
        public string Includes { get; set; }
        public string Not_included { get; set; }
        public string Notices_Policy { get; set; }
        public string Cancel_Refund { get; set; }
        public string Sdate { get; set; }
        public string Edate { get; set; }
        public System.DateTime Rdate { get; set; }
        public Nullable<bool> Usable { get; set; }
        public string Writer { get; set; }
        public string MainImgPath { get; set; }
        public string Price_d { get; set; }
        public string Price_w { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Startc { get; set; }
        public string Endc { get; set; }
        public string code { get; set; }
        public string days { get; set; }
        public string Notice { get; set; }
        public string Reservation { get; set; }
        public string Accommodations { get; set; }
        public string Cancel_Notice { get; set; }
        public string Seller_Info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courses> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay> Pay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TG_Image> TG_Image { get; set; }
    }
}
