//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supertalentoftheworld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.bbs_comment = new HashSet<bbs_comment>();
            this.BoardFile = new HashSet<BoardFile>();
            this.cal_memo = new HashSet<cal_memo>();
            this.history = new HashSet<history>();
            this.my_work = new HashSet<my_work>();
            this.New_work = new HashSet<New_work>();
            this.project_act = new HashSet<project_act>();
            this.project_act1 = new HashSet<project_act>();
            this.project_dir = new HashSet<project_dir>();
            this.work_list = new HashSet<work_list>();
        }
    
        public string user_id { get; set; }
        public string user_password { get; set; }
        public int idx { get; set; }
        public string company_id { get; set; }
        public string department_id { get; set; }
        public string user_name { get; set; }
        public string user_auth { get; set; }
        public System.DateTime write_date { get; set; }
        public string use_yn { get; set; }
        public int check_auth { get; set; }
        public string user_tel { get; set; }
        public string writer { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> con_date { get; set; }
        public string main_bg_color { get; set; }
        public string photo_profile { get; set; }
        public int alert_yn { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string manager_yn { get; set; }
        public string position { get; set; }
        public string language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bbs_comment> bbs_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardFile> BoardFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cal_memo> cal_memo { get; set; }
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<my_work> my_work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<New_work> New_work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_act> project_act { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_act> project_act1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_dir> project_dir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_list> work_list { get; set; }
    }
}
